from django.contrib import admin
from gym_app.models import *
# Register your models here.
admin.site.register([BussinessOwnerModel,
                     Payment_mode,
                     Enquiry,
                     Equipements,
                     Gender,
                     BloodGroup,
                     PrefferedTime,
                     Role,
                     Status,
                     ExtendedUserModel,
                     BA_Status,
                     MembershipPlan,
                     AssignTrainer,
                     Attendance,
                     Certifications,
                     Specializations,
                     TrainerProfile,
                     ActivityLevel,
                     Goal,
                     MemberProfile,
                     CustomizedPlan,
                     Schedule,
                     Week,
                     CommonDietPlan,
                     ScheduleStatus,
                     SlotBooking,
                     ShiftTiming,
                     Slot_Count,
                     ID_Proof,
                     Salary_management
                     ])