# Generated by Django 3.2.9 on 2023-08-22 13:46

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gym_app', '0066_assigntrainer_total_paid_amount'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='bussinessownermodel',
            name='gym_name',
        ),
        migrations.RemoveField(
            model_name='bussinessownermodel',
            name='logo',
        ),
        migrations.RemoveField(
            model_name='goal',
            name='added_by',
        ),
        migrations.RemoveField(
            model_name='membershipplan',
            name='added_by',
        ),
        migrations.AddField(
            model_name='extendedusermodel',
            name='expiry_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='extendedusermodel',
            name='join_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='prefferedtime',
            name='reset_date',
            field=models.DateField(default=datetime.date(2023, 8, 22)),
        ),
    ]
