# Generated by Django 3.2.9 on 2023-08-22 13:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('gym_app', '0068_extendedusermodel_fitness_goal'),
    ]

    operations = [
        migrations.AddField(
            model_name='extendedusermodel',
            name='membership_plan',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='gym_app.membershipplan'),
        ),
    ]
