# Generated by Django 3.2.9 on 2023-08-23 12:04

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gym_app', '0069_extendedusermodel_membership_plan'),
    ]

    operations = [
        migrations.AddField(
            model_name='extendedusermodel',
            name='certificate_photo',
            field=models.ImageField(blank=True, null=True, upload_to='certificates'),
        ),
        migrations.AddField(
            model_name='extendedusermodel',
            name='trainer_work_experience',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='extendedusermodel',
            name='height',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='extendedusermodel',
            name='weight',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='prefferedtime',
            name='reset_date',
            field=models.DateField(default=datetime.date(2023, 8, 23)),
        ),
    ]
