# Generated by Django 3.2.9 on 2023-08-24 10:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('gym_app', '0071_auto_20230824_1257'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='salary_management',
            name='added_by',
        ),
    ]
