# Generated by Django 3.2.9 on 2023-08-26 13:34

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gym_app', '0072_remove_salary_management_added_by'),
    ]

    operations = [
        migrations.AddField(
            model_name='extendedusermodel',
            name='amount_paid',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='extendedusermodel',
            name='pending_amount',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='extendedusermodel',
            name='total_paid_amount',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='prefferedtime',
            name='reset_date',
            field=models.DateField(default=datetime.date(2023, 8, 26)),
        ),
    ]
