# Generated by Django 3.2.9 on 2023-09-04 04:14

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gym_app', '0073_auto_20230826_1904'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='membershipplan',
            name='features',
        ),
        migrations.AddField(
            model_name='membershipplan',
            name='session',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='salary_management',
            name='absent',
            field=models.FloatField(default=0),
        ),
        migrations.AlterField(
            model_name='extendedusermodel',
            name='pending_amount',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='membershipplan',
            name='duration',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='prefferedtime',
            name='reset_date',
            field=models.DateField(default=datetime.date(2023, 9, 4)),
        ),
    ]
