# Generated by Django 3.2.9 on 2023-09-05 08:58

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gym_app', '0074_auto_20230904_0944'),
    ]

    operations = [
        migrations.AddField(
            model_name='extendedusermodel',
            name='gst',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='prefferedtime',
            name='reset_date',
            field=models.DateField(default=datetime.date(2023, 9, 5)),
        ),
    ]
