# Generated by Django 3.2.9 on 2023-09-05 10:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gym_app', '0075_auto_20230905_1428'),
    ]

    operations = [
        migrations.AddField(
            model_name='extendedusermodel',
            name='gst_amount',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
    ]
