# Generated by Django 4.2.1 on 2023-09-12 06:09

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gym_app', '0076_extendedusermodel_gst_amount'),
    ]

    operations = [
        migrations.AlterField(
            model_name='prefferedtime',
            name='reset_date',
            field=models.DateField(default=datetime.date(2023, 9, 12)),
        ),
        migrations.AlterField(
            model_name='salary_management',
            name='paid',
            field=models.FloatField(blank=True, default=0, null=True),
        ),
    ]
