# Generated by Django 3.2.9 on 2023-09-16 05:34

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gym_app', '0082_auto_20230914_1028'),
    ]

    operations = [
        migrations.AddField(
            model_name='extendedusermodel',
            name='add_on_plan',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='extendedusermodel',
            name='add_on_plan_price',
            field=models.FloatField(blank=True, default=0, null=True),
        ),
        migrations.AlterField(
            model_name='extendedusermodel',
            name='admission_date',
            field=models.DateField(blank=True, null=True, verbose_name='starting date'),
        ),
        migrations.AlterField(
            model_name='extendedusermodel',
            name='pending_amount',
            field=models.IntegerField(blank=True, default=0, null=True, verbose_name='balance'),
        ),
        migrations.AlterField(
            model_name='prefferedtime',
            name='reset_date',
            field=models.DateField(default=datetime.date(2023, 9, 16)),
        ),
    ]
