# Generated by Django 3.2.9 on 2023-09-16 06:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('gym_app', '0083_auto_20230916_1104'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='extendedusermodel',
            name='add_on_plan_price',
        ),
    ]
