# Generated by Django 4.2.1 on 2023-09-19 12:17

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('gym_app', '0085_alter_extendedusermodel_user_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='extendedusermodel',
            name='user',
            field=models.OneToOneField(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='extendeduser', to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
    ]
