# Generated by Django 4.2.1 on 2023-10-04 05:20

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gym_app', '0089_extendedusermodel_email_sent_status_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='extendedusermodel',
            name='follow_up_status',
            field=models.CharField(choices=[('Pending', 'Pending'), ('Closed', 'Closed')], default='Pending', max_length=25),
        ),
        migrations.AlterField(
            model_name='prefferedtime',
            name='reset_date',
            field=models.DateField(default=datetime.date(2023, 10, 4)),
        ),
    ]
