# Generated by Django 4.2.1 on 2023-10-04 05:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gym_app', '0091_remove_extendedusermodel_follow_up_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='enquiry',
            name='follow_up_status',
            field=models.CharField(choices=[('Pending', 'Pending'), ('Closed', 'Closed')], default='Pending', max_length=25),
        ),
    ]
