# Generated by Django 4.2.1 on 2023-10-06 07:26

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gym_app', '0092_enquiry_follow_up_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='prefferedtime',
            name='reset_date',
            field=models.DateField(default=datetime.date(2023, 10, 6)),
        ),
        migrations.DeleteModel(
            name='Attendances',
        ),
    ]
