# Generated by Django 4.2.1 on 2023-10-06 07:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gym_app', '0093_alter_prefferedtime_reset_date_delete_attendances'),
    ]

    operations = [
        migrations.CreateModel(
            name='Attendances',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('employee_id', models.CharField(blank=True, max_length=250, null=True)),
                ('attendance_date', models.DateField(auto_now_add=True)),
                ('punch_log', models.TimeField(blank=True, null=True)),
            ],
        ),
    ]
