# Generated by Django 4.2.1 on 2023-10-10 09:41

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gym_app', '0095_alter_attendances_attendance_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='attendances',
            name='employee_name',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='prefferedtime',
            name='reset_date',
            field=models.DateField(default=datetime.date(2023, 10, 10)),
        ),
    ]
