# Generated by Django 4.2.1 on 2023-10-10 11:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gym_app', '0096_attendances_employee_name_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='extendedusermodel',
            name='attendance_id',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
