# Generated by Django 4.2.1 on 2023-10-11 05:00

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gym_app', '0097_extendedusermodel_attendance_id'),
    ]

    operations = [
        migrations.CreateModel(
            name='Attendance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('employee_id', models.CharField(blank=True, max_length=250, null=True)),
                ('employee_name', models.CharField(blank=True, max_length=50, null=True)),
                ('role', models.TimeField(blank=True, null=True)),
                ('attendance_date', models.DateTimeField(blank=True, null=True)),
            ],
        ),
        migrations.AlterField(
            model_name='prefferedtime',
            name='reset_date',
            field=models.DateField(default=datetime.date(2023, 10, 11)),
        ),
    ]
