# Generated by Django 4.2.1 on 2023-10-11 09:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gym_app', '0098_attendance_alter_prefferedtime_reset_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='attendance',
            name='role',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
