# Generated by Django 4.2.1 on 2023-10-26 05:34

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gym_app', '0099_alter_attendance_role'),
    ]

    operations = [
        migrations.AddField(
            model_name='enquiry',
            name='membership_expiry_status',
            field=models.CharField(choices=[('Pending', 'Pending'), ('Closed', 'Closed')], default='Pending', max_length=25),
        ),
        migrations.AlterField(
            model_name='prefferedtime',
            name='reset_date',
            field=models.DateField(default=datetime.date(2023, 10, 26)),
        ),
    ]
