# Generated by Django 4.2.1 on 2023-10-26 05:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('gym_app', '0100_enquiry_membership_expiry_status_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='enquiry',
            name='membership_expiry_status',
        ),
    ]
