# Generated by Django 4.2.1 on 2023-10-26 10:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gym_app', '0102_extendedusermodel_membership_expiry_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='extendedusermodel',
            name='email_sent_status_pending_payment',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='extendedusermodel',
            name='email_sent_status',
            field=models.BooleanField(default=False, verbose_name='email sent status of membership expiry'),
        ),
    ]
