# Generated by Django 4.2.1 on 2023-11-08 12:03

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gym_app', '0103_extendedusermodel_email_sent_status_pending_payment_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Attendances',
        ),
        migrations.AlterField(
            model_name='prefferedtime',
            name='reset_date',
            field=models.DateField(default=datetime.date(2023, 11, 8)),
        ),
    ]
